
sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

env:
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

addons:
  sonarcloud:
    organization: "vinaykp-github"
    token:
      secure: $SONAR_TOKEN


script:
  - mvn clean install -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=vinaykp/scoutsapi-spring
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
